### ISSUE TITLE
Module not found issue

### ISSUE THREAD

**Issue by LyraaaBelacqua** [L4STeam/linux#12]
When it tried to execute "sudo modprobe sch_dualpi2"

I encountered the following error

modprobe: FATAL: Module sch_dualpi2 not found in directory /lib/modules/5.15.0-48-generic

I was wondering how to resolve this issue. Thanks!

**Comment by minuscat** [comment]
It looks like you did not load the Prague kernel correctly, and you are still using the generic kernel 5.15.0-48-generic.
Check the kernel you are using now by "uname -a".

You can change the default kernel in /etc/default/grub and run "update-grub" to make sure the Prague kernel is used correctly after reboot.
