### ISSUE TITLE
BBR not clearing ECT(1) on release

### ISSUE THREAD

**Issue by koen0607** [L4STeam/linux#15]
When having BBR2 enabled by default or on a socket, before switching to another non-scalable congestion control via a socket option, then the non-scalable congestion control will still use ECT(1) instead of ECT(0). Solution id to clear the TCP_ECN_ECT_1 flag from the ecn_flags during release.

**Comment by minuscat** [comment]
This is indeed an issue for BBR2, but shall be fixed by BBR team separately.
