### ISSUE TITLE
Issue with ECN Marking in Experimental Network Configuration. 

### ISSUE THREAD

**Issue by Anjali-19** [L4STeam/linux#29]
Hi everyone,

I'm encountering an issue with obtaining a CE mark via a router. Below is the topology I'm utilizing for an experiment, where h1 and h2 serve as senders, h3 as the receiver, and there exists a bottleneck bandwidth of 10 mbps between routers r1 and r2, with a propagation delay of 10ms. Prague is being employed as a scalable congestion control from flow h1 to h3, while cubic serves as the classic congestion control from flow h2 to h3.

![Topology](https://github.com/L4STeam/linux/assets/66936877/4089ee67-a904-45e2-9edb-dc4b91223644)

To facilitate the operation of Prague and dualpi2, I've incorporated the kernel tree from (https://github.com/L4STeam/linux) and installed iproute2 from (https://github.com/L4STeam/iproute2). Additionally, I'm conducting the experiment using Linux namespaces.

Here are the sysctl commands I've used to configure the experiment:

sysctl -w net.ipv4.tcp_congestion_control=prague (at h1)
sysctl -w net.ipv4.tcp_congestion_control=cubic (at h2)
sysctl -w net.ipv4.tcp_ecn=3 (enabled Accurate ECN at h1, r1, r2, and h3)
sysctl -w net.ipv4.tcp_ecn=1 (classic ECN at h2)
These are the parameters I've set for running the experiment:

limit: 10000
target: 15ms
tupdate: 16ms
alpha: 0.16
beta: 3.25
step.thresh: 1ms
step.in_packets: false
c_protection: 10%
ecn_mask: 1
coupling_factor: 2
drop_overload: true
drop_early: false
split_gso: true

I'm using Wireshark to capture packets, but I'm not observing any ECN marking whereas I can see ECT(1) for scalable traffic and ECT(0) for classic traffic. Any assistance in resolving this issue would be greatly appreciated.

Thank you.

**Comment by minuscat** [comment]
This issue is closed after communication with Anjali directly in email
