### ISSUE TITLE
Issue in CE marking

### ISSUE THREAD

**Issue by zanearniel** [L4STeam/linux#32]
Hi,
Im facing the same issue as #29 when im using dualpi2 in my router.The packets enter the dualpi2 qdisc and the ECT(1) packets are perfectly classified into the L4S queue but they are not marked as CE.It seems there is no queue building happening.When I checked the qdisc_qlen in the dualpi2 qdisc,its always 1 and it never increases.At a time only one packet enters the qdisc.Any help in resolving this issue?  @minuscat 
Thanks

**Comment by minuscat** [comment]
Hi, could you share the dualpi2 parameters you used? This potentially due to you use non-default DualPI2 parameters or you have bottleneck somewhere else. And I think your situation is more like the latter, so can you check your setup indeed have the bottleneck setup at the Dualpi2 Qdisc?

**Comment by zanearniel** [comment]
Hi.I only used the default parameters for dualpi2,didnt change anything.Ive added debugs to check if the packets enter the classic and L4S queue and it does enter accordingly.But the issue is my bottleneck initially didnt have tc utility properly setup,the packets didnt even enter the qdisc so I had to redirect the packet path to enter through qdisc by using the dev_queue_xmit() fn .Maybe my qdisc is not setup properly?But the qlen is always 1
