### ISSUE TITLE
tcp_prague_info prague_enabled?

### ISSUE THREAD

**Issue by randomizedcoder** [L4STeam/linux#34]
I wonder if prague_enabled is required? dctcpinfo included enabled as uint16, but bbrinfo doesn't have enabled.  I guess bbr took the view that simply by virtue of this struct coming through, then bbr is enabled.

```
struct tcp_prague_info {
	__u64	prague_alpha;
	__u64	prague_frac_cwnd;
	__u64   prague_rate_bytes;
	__u32	prague_max_burst;
	__u32	prague_round;
	__u32	prague_rtt_target;
	bool	prague_enabled;          <---- ??
};
```

https://github.com/L4STeam/linux/blob/56eae305cddf172b87c54d8a61db8d1e9e2204f0/include/uapi/linux/inet_diag.h#L237  

```
struct tcp_dctcp_info {
 	__u16	dctcp_enabled;     <-----
 	__u16	dctcp_ce_state;
	__u32	dctcp_alpha;
	__u32	dctcp_ab_ecn;
	__u32	dctcp_ab_tot;
};
```

No enabled
```
	struct tcp_bbr_info {
		/* u64 bw: max-filtered BW (app throughput) estimate in Byte per sec: */
		__u32	bbr_bw_lo;		/* lower 32 bits of bw */
		__u32	bbr_bw_hi;		/* upper 32 bits of bw */
		__u32	bbr_min_rtt;		/* min-filtered RTT in uSec */
		__u32	bbr_pacing_gain;	/* pacing gain shifted left 8 bits */
		__u32	bbr_cwnd_gain;		/* cwnd gain shifted left 8 bits */
	};
```

https://github.com/L4STeam/linux/blob/56eae305cddf172b87c54d8a61db8d1e9e2204f0/include/uapi/linux/inet_diag.h#L217

**Comment by minuscat** [comment]
Hello, this prague_enabled will be removed when mainlining to the Linux kernel tree
