### ISSUE TITLE
Set up GitHub actions to build dpkg, etc.

### ISSUE THREAD

**Issue by larseggert** [L4STeam/linux#4]
It would be great if you could set up a GitHub Actions workflow that would build Debian packages, etc. of the kernel for easy experimentation.

(You probably want to do something like this for CI reasons anyway.)

**Comment by oliviertilmans** [comment]
Hi,

There is already an action that builds *deb archive for the kernel
and uploads in as artifact;
At the time at which it was setup, it was not possible to link the
latest artefact--i.e., only urls such as 
https://github.com/L4STeam/linux/suites/1514802885/artifacts/26645899
would work. I have not followed the latest action updates, did
that change?

I'll note that I should add one for the iproute2 package though...


Best,
Olivier

**Comment by larseggert** [comment]
There is some discussion and an approach described in https://github.com/actions/upload-artifact/issues/21, but I have not used it myself.

**Comment by larseggert** [comment]
Also, the https://github.com/L4STeam/linux/suites/1514802885/artifacts/26645899 URL only works if one is logged into GitHub, so can't be easily used with `wget`, etc.

**Comment by oliviertilmans** [comment]
Thanks for suggestion.
You should now be able to access *.debs for the kernel from the following
stable URL:
https://github.com/L4STeam/linux/releases/download/testing-build/l4s-testing.zip

I'll check whether it is feasible to also include an iproute2 as part of
that release zip.

**Comment by oliviertilmans** [comment]
The testing-build tag will always have *.debs for the linux-image, linux-headers, linux-libc,
 and iproute2.

I could access these anonymously from: https://github.com/L4STeam/linux/releases/download/testing-build/l4s-testing.zip

Given that the tag will always float with HEAD, you can find the underlying commit from this tree in the kernel version tag; i.e., downloading this zip on two different days might give two different zips...

**Comment by larseggert** [comment]
Thanks, that works for me!

**Comment by larseggert** [comment]
Which distro and version should this kernel work with? I tried both Ubuntu bionic and groovy, and both hang during boot.

**Comment by larseggert** [comment]
Specifically, bionic gets stuck during `systemd` initialization, and groovy can't find the root file system.

**Comment by larseggert** [comment]
I think the problem is that your CI build is doing `make defconfig`. You should probably use a config such as https://kernel.ubuntu.com/~kernel-ppa/config/groovy/linux/5.4.0-26.30/amd64-config.flavour.generic to make a kernel available that can boot a distro.

**Comment by oliviertilmans** [comment]
@larseggert I updated the action to use a base ubuntu kernel; hopefully this will solve your issues. My test machines seem to mostly use drivers part of defconfig...

**Comment by larseggert** [comment]
Thanks! I will test the new build tomorrow.

**Comment by larseggert** [comment]
This seems to work better, but there is still an issue. Although the kernel config you use has `CONFIG_VBOXSF_FS=m`, the `vboxfs` kernel module isn't installed under `/lib/modules/`.

**Comment by larseggert** [comment]
And I need `vboxfs` for https://github.com/larseggert/l4s-box (FYI)

**Comment by oliviertilmans** [comment]
It is actually surprising that this config knob is even present at all...

Vboxfs was introduced in 5.4-rc7 
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/drivers/staging/vboxsf/Kconfig?id=df4028658f9dd7f82fd190e9db5bd82c05f94625
and nuked out in -rc8,
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=0e3f1ad80fc8cb0c517fd9a9afb22752b741fa76
and finally reintroduced in 
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/fs/vboxsf/Kconfig?id=0fd169576648452725fa2949bf391d10883d3991
which is part of 5.6.
For old reasons, this tree is forked from -rc3 this predates vboxsf.

Is ubuntu somehow patching this in? Looking at their 5.4.60 tree (from which we get our config), that does
not seem to be the case...
https://git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux/+git/focal/tree/fs?h=Ubuntu-5.4.0-60.67
(CONFIG_VBOXSF_FS should match a fs/vboxsf module).

One possible workaround would be to install
[virtualbox-guest-dkms](https://packages.ubuntu.com/groovy/virtualbox-guest-dkms)
in the box prior to updating the kernel.

**Comment by larseggert** [comment]
> One possible workaround would be to install [virtualbox-guest-dkms](https://packages.ubuntu.com/groovy/virtualbox-guest-dkms) in the box prior to updating the kernel.

Let me try that!

**Comment by larseggert** [comment]
I needed both `virtualbox-guest-dkms` and `virtualbox-guest-utils`, but that fixed it.
