### ISSUE TITLE
cwr_stamp not initialized might cause the first CWR to be skipped

### ISSUE THREAD

**Issue by koen0607** [L4STeam/linux#6]
proposed to init cwr_stamp with a value that is 10 seconds ago:

	ca->cwr_stamp = tp->tcp_mstamp - 10000000; // init 10 seconds ago

**Comment by oliviertilmans** [comment]
It is 0-initialized (like the rest of the icsk_ca_priv storage) when the socket is initialized/assigned a congestion control:
https://github.com/L4STeam/linux/blob/testing/net/ipv4/tcp_cong.c#L170
