### ISSUE TITLE
incorrect path spec in README.md: sudo dpkg --install debian_build/*

### ISSUE THREAD

**Issue by nealcardwell** [L4STeam/linux#9]
In the README.md, the "Installation (debian derivatives)" section mentions:

  sudo dpkg --install debian_build/*

AFAICT there is no debian_build/ directory at this point, and instead this should be:

  sudo dpkg --install *.deb

That *.deb form seems to work fine (installs correctly and boots fine, at least on Google Cloud).

Thanks!

**Comment by minuscat** [comment]
Indeed, this is incorrect and shall be fixed in README.md

**Comment by minuscat** [comment]
Change the workflow and close the issue
